spring:
  application:
    name: esure
    version: 1.0.0
    description: ESure APIS
    jwt:
      jwtSecret: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D
      jwtExpirationMs: 86400000
      jwtCookie: QPXYPUQZRE

  datasource:
    url: jdbc:mariadb://localhost:3306/esure_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: masterpwd@2024
    driver-class-name: org.mariadb.jdbc.Driver

  r2dbc:
    url: r2dbc:mariadb://localhost:3306/esure_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: masterpwd@2024

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

  main:
    allow-bean-definition-overriding: true

  data:
    r2dbc:
      repositories:
        enabled: true
    jdbc:
      repositories:
        enabled: false

server:
  address: 0.0.0.0
  port: 8065

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG


egroupx:
  services:
    fsp:
      endpointUrl: https://test.fspsolutions.com
      apiKey: 1Am}@vdV0mJV[J4vL=k?!e+H~3=].NP2

    pol360:
      endpointUrl: https://web02.pol360.co.za
      tokenGenClientName: RoyaleCrownsFinancialServices
      tokenUUID: 9eab086c-0dc1-4e5e-8f46-6b8e6e2a3656
      userName: damien@pol360.co.za
      password: 360API$360#

    medicalAid:
      pfisterEmailAddress: info@pfister.co.za
      esureEmailAddress: medicalaid@esurecover.co.za

    namescan:
      url: https://api.namescan.io/v3
      apiKey: 06A85DBCDCAD492B80FC3E1C18FAB4C2

    marisit:
      url: https://online.marisit.co.za
      username: jm980514uts
      password: JOsh078112$%&

    securecitizen:
      url: https://citizenapi.securecitizen.cloud/Citizen

    otpSMS:
      endpoint: https://backoffice.payflo.co.za
      apiKey: MpqPmOStn1VBGIsJI3nPX25NbOXAad03f7L1jeD

  email:
    host: mail.esurecover.co.za
    port: 587
    sender: noreply@esurecover.co.za
    recipient: support@esurecover.co.za
    username: noreply@esurecover.co.za
    password: noreply7860@
    sendEmail: true
    backgroundImage: https://onboarding.esurecover.com/assets/esure_email_bg.png
    logo: https://onboarding.esurecover.com/assets/esure_email_logo.png

  files:
    dir: C:/Users/FrancisChinyanga/Desktop/files/

management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: swagger-ui/index.html