spring:
  application:
    name: esure
    version: 1.0.0
    description: ESure APIS
    jwt:
      jwtSecret: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D
      jwtExpirationMs: 86400000
      jwtCookie: QPXYPUQZRE

  datasource:
    url: jdbc:mariadb://102.131.62.24:3306/esure_db?allowPublicKeyRetrieval=true&useSSL=false
    username: esure_uat
    password: qbAS7GIz3BIrC6Ioget8IxjsL
    driver-class-name: org.mariadb.jdbc.Driver

  r2dbc:
    url: r2dbc:mariadb://102.131.62.24:3306/esure_db?allowPublicKeyRetrieval=true&useSSL=false
    username: esure_uat
    password: qbAS7GIz3BIrC6Ioget8IxjsL

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

  main:
    allow-bean-definition-overriding: true

  data:
    r2dbc:
      repositories:
        enabled: true
    jdbc:
      repositories:
        enabled: false

server:
  address: 0.0.0.0
  port: 8065

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG


egroupx:
  services:
    fsp:
      endpointUrl: https://www.fspsolutions.com
      apiKey: 1Am}@vdV0mJV[J4vL=k?!e+H~3=].NP2

    pol360:
      endpointUrl: https://web02.pol360.co.za
      tokenGenClientName: RoyaleCrownsFinancialServices
      tokenUUID: 9eab086c-0dc1-4e5e-8f46-6b8e6e2a3656
      userName: damien@pol360.co.za
      password: 360API$360#

    medicalAid:
      emailAddress: chinyangaf@gmail.com

    namescan:
      url: https://api.namescan.io/v3
      apiKey: 06A85DBCDCAD492B80FC3E1C18FAB4C2

    marisit:
      url: https://online.marisit.co.za
      username: jm980514uts
      password: JOsh078112$%&

    securecitizen:
      url: https://citizenapi.securecitizen.cloud/Citizen

    otpSMS:
      endpoint: http://102.131.60.77:8088

  email:
    host: mail.ezaga.co.za
    port: 587
    sender: noreply@ezaga.co.za
    recipient: registration@ezitransact.co.za
    username: noreply@ezaga.co.za
    password: Dv1E}^VR5L?L
    sendEmail: true

  files:
    dir:

management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: swagger-ui/index.html